/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康檢查
         * @description 檢查模擬器服務是否運作中
         */
        get: operations["getSimulatorHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得模擬參數
         * @description 取得目前的模擬電表參數設定
         */
        get: operations["getSimulatorConfig"];
        put?: never;
        /**
         * 修改模擬參數
         * @description 修改模擬電表的參數設定。所有參數都是可選的，只會更新有提供的參數。
         *
         *     **功率計算公式：**
         *     ```
         *     P (kW) = √3 × 380V × current_base_a × power_factor / 1000
         *     ```
         *
         *     **快速參考：**
         *     - current_base_a=100, power_factor=0.85 → ~56 kW
         *     - current_base_a=180, power_factor=0.85 → ~101 kW (會觸發告警)
         */
        post: operations["setSimulatorConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inject-fault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注入故障模式
         * @description 設定故障模式以測試告警機制：
         *     - `none`: 正常運作
         *     - `zero`: 所有數值歸零
         *     - `freeze`: 數值凍結不更新
         */
        post: operations["injectFault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/electricity_measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢歷史電力量測資料
         * @description 使用 PostgREST 語法查詢 TimescaleDB 中的歷史電力量測資料（electricity_measurements 表）。
         *
         *     **支援的運算子：**
         *     - `eq.` 等於
         *     - `gt.` 大於
         *     - `gte.` 大於等於
         *     - `lt.` 小於
         *     - `lte.` 小於等於
         *     - `neq.` 不等於
         *
         *     **範例：**
         *     - `?power_kw=gt.50` - 功率大於 50kW
         *     - `?time=gte.2026-04-23T00:00:00` - 時間大於等於指定時間
         */
        get: operations["getMeasurements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/factory_measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢工廠量測資料
         * @description 使用 PostgREST 語法查詢 TimescaleDB 中的工廠 PLC 與 JSON 感測器資料（factory_measurements 表）。
         *
         *     **來源設備：**
         *     - `plc-001`: KC Modbus PLC simulator，包含 temperature、humidity、motor_speed、pump_on、valve_open、pressure
         *     - `sensor-001`: KC MQTT JSON sensor，包含 temperature、humidity
         */
        get: operations["getFactoryMeasurements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provisioning/alerting/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新載入告警設定
         * @description 重新載入 provisioning 目錄下的告警規則和聯絡點設定
         */
        post: operations["reloadAlertingConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provisioning/dashboards/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新載入儀表板設定
         * @description 重新載入 provisioning 目錄下的儀表板設定
         */
        post: operations["reloadDashboardsConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/provisioning/datasources/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新載入資料來源設定
         * @description 重新載入 provisioning 目錄下的資料來源設定
         */
        post: operations["reloadDatasourcesConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prometheus/grafana/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得告警規則狀態
         * @description 取得所有告警規則的目前狀態
         */
        get: operations["getAlertRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertmanager/grafana/api/v2/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得目前觸發中的告警
         * @description 取得所有正在觸發 (firing) 的告警
         */
        get: operations["getActiveAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/uid/{uid}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 檢查資料來源健康狀態
         * @description 檢查指定資料來源是否可以連線
         */
        get: operations["checkDatasourceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertmanager/grafana/config/api/v1/receivers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 測試通知接收者
         * @description 發送測試通知到指定的接收者 (例如 Telegram)
         */
        post: operations["testNotificationReceiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** device-service 健康檢查（雙 pool 狀態，FR-314） */
        get: operations["deviceHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出裝置（OPS；可依 status / stale / type 過濾，支援分頁與排序） */
        get: operations["listDevices"];
        put?: never;
        /** 建立 candidate 裝置（OPS） */
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        /** 讀取單一裝置（OPS） */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** 退役裝置（OPS；凍結裝置回 409，改用 /reject） */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        /** 更新裝置中繼資料（OPS；凍結欄位須走 /override） */
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/devices/{device_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接受 AI 推論 → confirmed（OPS） */
        post: operations["confirmDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 人工修正後接受（OPS；帶 freeze-override token） */
        post: operations["overrideDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒絕 → retired（OPS） */
        post: operations["rejectDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/ai-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交人類修正回饋（OPS，FR-330）
         * @description 寫入 device_corrections（永久保留，注入後續分類 prompt）。內容違規回 400。
         *     rerun_classification=true → commit 後觸發 on-demand reclassify（best-effort）。
         *     demote_to_candidate=true → confirmed→candidate（其他狀態回 409）。
         */
        post: operations["createAiFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出該裝置歷史 corrections（OPS，內部用） */
        get: operations["listCorrections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/corrections/{correction_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 失效一筆 correction（OPS，FR-341；之後不再注入 prompt） */
        post: operations["deactivateCorrection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/human-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 讀取人工審查 digest（OPS，§8.4；不現呼 LLM） */
        get: operations["humanReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        /** 列出裝置 signals（OPS） */
        get: operations["listSignals"];
        put?: never;
        /** 新增一個 active signal（OPS；凍結裝置須走 /override） */
        post: operations["addSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/signals/{signal_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 退役一個 active signal（OPS；凍結紀錄須走 /override） */
        delete: operations["deleteSignal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeviceCreate: {
            /** @example sim-002 */
            device_id: string;
            /** @description electricity / temperature / unknown ... */
            device_type?: string | null;
            /** @example modbus_tcp */
            protocol?: string | null;
            vendor?: string | null;
            model?: string | null;
            location?: string | null;
            /**
             * @description 來源 gateway
             * @example ems-gateway
             */
            gateway_id?: string | null;
        };
        /** @description 非凍結欄位的部分更新；凍結欄位須走 /override。所有欄位皆選填。 */
        DeviceUpdate: {
            device_type?: string | null;
            protocol?: string | null;
            vendor?: string | null;
            model?: string | null;
            location?: string | null;
            gateway_id?: string | null;
        };
        DeviceOut: {
            device_id: string;
            device_type?: string | null;
            /** @description candidate / confirmed / retired */
            status: string;
            protocol?: string | null;
            vendor?: string | null;
            model?: string | null;
            location?: string | null;
            gateway_id?: string | null;
            /** @description ai / human / manual_override / migration_backfill */
            classified_by?: string | null;
            /**
             * Format: float
             * @description AI 分類信心值（0–1；未分類為 null）
             */
            ai_confidence?: number | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        SignalCreate: {
            signal_name: string;
            unit?: string | null;
            /** @description float / int / bool / string / enum */
            datatype?: string | null;
            /** @description read / write / read_write */
            direction?: string | null;
            source_ref?: string | null;
        };
        SignalOut: {
            id: number;
            device_id: string;
            signal_name: string;
            unit?: string | null;
            datatype?: string | null;
            direction?: string | null;
            /** @description active / retired */
            status: string;
        };
        OverrideRequest: {
            /** @description 人工指定的正確型別（凍結欄位） */
            device_type: string;
            /**
             * @description 人工指定的 signals（覆寫 AI 推論）
             * @default []
             */
            signals: components["schemas"]["SignalCreate"][];
        };
        /**
         * @description provenance（prompt_version_at_correction、created_by_key_id、salt_version）由伺服端
         *     stamp，非 client 欄位。
         */
        CorrectionCreate: {
            /** @enum {string} */
            verdict: "wrong_classification" | "wrong_signals" | "wrong_unit" | "missed_signal" | "good_with_note";
            corrected_device_type?: string | null;
            corrected_signals?: components["schemas"]["SignalCreate"][] | null;
            /** @description 人類修正說明；NFKC + 長度(30–500) + 結構/秘密/注入字串檢查（§7.3a），永久保留並注入後續分類 prompt。 */
            human_explanation: string;
            /**
             * @description commit 後觸發 on-demand reclassify（best-effort，失敗只記 warning）。
             * @default false
             */
            rerun_classification: boolean;
            /**
             * @description confirmed→candidate（其他狀態回 409）。
             * @default false
             */
            demote_to_candidate: boolean;
        };
        CorrectionDeactivateRequest: {
            /** @description 失效理由；同 human_explanation 走 §7.3a 檢查（長度 30–500、結構/秘密/注入）。 */
            reason: string;
        };
        CorrectionOut: {
            id: number;
            device_id: string;
            verdict: string;
            corrected_device_type?: string | null;
            corrected_signals?: {
                [key: string]: unknown;
            }[] | null;
            human_explanation: string;
            /** Format: date-time */
            created_at?: string | null;
            /** @description HMAC key id（非原始金鑰） */
            created_by_key_id: string;
            salt_version: string;
            prompt_version_at_correction?: string | null;
            applied_count: number;
            /** Format: date-time */
            last_applied_at?: string | null;
            is_active: boolean;
            /** Format: date-time */
            deactivated_at?: string | null;
            deactivation_reason?: string | null;
        };
        /** @description 人工審查 digest（§8.4）；不現呼 LLM，讀既有快取。 */
        DigestOut: {
            device_id: string;
            /** @description digest.py 建的固定形狀 JSON */
            digest: {
                [key: string]: unknown;
            };
            /** @description llm / system_fallback */
            summary_source: string;
            /** Format: date-time */
            generated_at?: string | null;
            provider?: string | null;
            model?: string | null;
            prompt_version?: string | null;
        };
        /** @description device-service /healthz（FR-314）；degraded 時回 503。 */
        HealthOut: {
            /** @description ok / degraded */
            status: string;
            /** @description 各 DB pool 狀態（ai / ops → ok|...） */
            pools: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            /**
             * @description 服務狀態
             * @enum {string}
             */
            status: "ok";
        };
        SimulatorConfig: {
            /**
             * Format: float
             * @description 電壓雜訊標準差 (V)
             * @example 3
             */
            noise_voltage_v?: number;
            /**
             * Format: float
             * @description 基礎電流 (A)
             * @example 100
             */
            current_base_a?: number;
            /**
             * Format: float
             * @description 電流波動幅度 (A)
             * @example 40
             */
            current_swing_a?: number;
            /**
             * Format: float
             * @description 電流雜訊標準差 (A)
             * @example 2
             */
            noise_current_a?: number;
            /**
             * Format: float
             * @description 功率因數
             * @example 0.85
             */
            power_factor?: number;
            /**
             * Format: float
             * @description 負載週期秒數
             * @example 3600
             */
            period_seconds?: number;
            /**
             * @description 目前的故障模式
             * @enum {string}
             */
            fault_mode?: "none" | "zero" | "freeze";
        };
        FaultResponse: {
            /**
             * @description 已設定的故障模式
             * @enum {string}
             */
            fault_mode?: "none" | "zero" | "freeze";
        };
        ErrorResponse: {
            /** @description 錯誤訊息 */
            error?: string;
        };
        Measurement: {
            /**
             * Format: date-time
             * @description 量測時間 (UTC)
             * @example 2026-04-23T10:30:00Z
             */
            time: string;
            /**
             * @description 設備 ID
             * @example sim-001
             */
            device_id: string;
            /**
             * Format: float
             * @description 電壓 (V)
             * @example 381.2
             */
            voltage?: number;
            /**
             * Format: float
             * @description 電流 (A)
             * @example 105.3
             */
            current?: number;
            /**
             * Format: float
             * @description 功率 (kW)
             * @example 58.7
             */
            power_kw?: number;
            /**
             * Format: float
             * @description 累計電量 (kWh)
             * @example 1234.56
             */
            energy_kwh?: number;
        };
        FactoryMeasurement: {
            /**
             * Format: date-time
             * @description 量測時間 (UTC)
             * @example 2026-04-27T09:00:00Z
             */
            time: string;
            /**
             * @description 設備 ID
             * @example plc-001
             */
            device_id: string;
            /**
             * @description 設備類型
             * @example plc
             * @enum {string}
             */
            device_type?: "plc" | "sensor";
            /**
             * Format: float
             * @description 溫度
             * @example 25.3
             */
            temperature?: number;
            /**
             * Format: float
             * @description 濕度 (%RH)
             * @example 55.2
             */
            humidity?: number;
            /**
             * Format: float
             * @description 馬達轉速 (RPM)
             * @example 1500
             */
            motor_speed?: number;
            /**
             * @description 幫浦狀態
             * @example true
             */
            pump_on?: boolean;
            /**
             * @description 閥門狀態
             * @example false
             */
            valve_open?: boolean;
            /**
             * Format: float
             * @description 壓力 (kPa)
             * @example 1013
             */
            pressure?: number;
        };
        AlertRulesResponse: {
            /** @example success */
            status?: string;
            data?: {
                groups?: {
                    /** @example EMS-功率告警 */
                    name?: string;
                    rules?: {
                        /** @example 功率超限 (power_kw > 100 kW) */
                        name?: string;
                        /**
                         * @example firing
                         * @enum {string}
                         */
                        state?: "inactive" | "pending" | "firing";
                    }[];
                }[];
            };
        };
        ActiveAlert: {
            labels?: {
                /** @example 功率超限 (power_kw > 100 kW) */
                alertname?: string;
                /** @example warning */
                severity?: string;
            };
            annotations?: {
                /** @example 功率超過 100 kW */
                summary?: string;
                /** @example 過去 5 分鐘平均 power_kw 超過 100 kW，請確認現場狀況 */
                description?: string;
            };
            /**
             * Format: date-time
             * @example 2026-04-23T10:30:00Z
             */
            startsAt?: string;
            status?: {
                /**
                 * @example active
                 * @enum {string}
                 */
                state?: "active" | "suppressed";
            };
        };
        DatasourceHealthResponse: {
            /**
             * @example OK
             * @enum {string}
             */
            status?: "OK" | "ERROR";
            /** @example Connection successful */
            message?: string;
        };
        TestReceiverRequest: {
            receivers: {
                /** @example Telegram */
                name?: string;
                grafana_managed_receiver_configs?: {
                    /** @example telegram-main */
                    uid?: string;
                    /** @example Telegram */
                    name?: string;
                    /** @example telegram */
                    type?: string;
                    settings?: {
                        /** @description Telegram Bot Token */
                        bottoken?: string;
                        /** @description Telegram Chat ID */
                        chatid?: string;
                        /** @description 測試訊息內容 */
                        message?: string;
                    };
                }[];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSimulatorHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服務正常運作 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getSimulatorConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目前的模擬參數 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "noise_voltage_v": 3,
                     *       "current_base_a": 100,
                     *       "current_swing_a": 40,
                     *       "noise_current_a": 2,
                     *       "power_factor": 0.85,
                     *       "period_seconds": 3600,
                     *       "fault_mode": "none"
                     *     }
                     */
                    "application/json": components["schemas"]["SimulatorConfig"];
                };
            };
        };
    };
    setSimulatorConfig: {
        parameters: {
            query?: {
                /** @description 電壓雜訊標準差 (V) */
                noise_voltage_v?: number;
                /** @description 基礎電流 (A)，直接影響功率大小 */
                current_base_a?: number;
                /** @description 電流波動幅度 (A) */
                current_swing_a?: number;
                /** @description 電流雜訊標準差 (A) */
                noise_current_a?: number;
                /** @description 功率因數 (0-1) */
                power_factor?: number;
                /** @description 負載週期秒數 */
                period_seconds?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 更新後的參數 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorConfig"];
                };
            };
        };
    };
    injectFault: {
        parameters: {
            query: {
                /** @description 故障模式 */
                mode: "none" | "zero" | "freeze";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 故障模式已設定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "fault_mode": "freeze"
                     *     }
                     */
                    "application/json": components["schemas"]["FaultResponse"];
                };
            };
            /** @description 無效的故障模式 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMeasurements: {
        parameters: {
            query?: {
                /**
                 * @description 選擇要回傳的欄位 (逗號分隔)
                 * @example time,power_kw,voltage
                 */
                select?: string;
                /**
                 * @description 依設備 ID 過濾 (使用 eq.xxx 格式)
                 * @example eq.sim-001
                 */
                device_id?: string;
                /**
                 * @description 依時間過濾 (使用 gte.xxx 或 lte.xxx 格式)
                 * @example gte.2026-04-23T00:00:00
                 */
                time?: string;
                /**
                 * @description 依功率過濾 (使用 gt.xxx, lt.xxx 等格式)
                 * @example gt.50
                 */
                power_kw?: string;
                /** @description 依電壓過濾 */
                voltage?: string;
                /** @description 依電流過濾 */
                current?: string;
                /**
                 * @description 排序欄位 (欄位名.asc 或 欄位名.desc)
                 * @example time.desc
                 */
                order?: string;
                /**
                 * @description 限制回傳筆數
                 * @example 10
                 */
                limit?: number;
                /**
                 * @description 跳過前 N 筆
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 量測資料列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "time": "2026-04-23T10:30:00Z",
                     *         "device_id": "sim-001",
                     *         "voltage": 381.2,
                     *         "current": 105.3,
                     *         "power_kw": 58.7,
                     *         "energy_kwh": 1234.56
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Measurement"][];
                };
            };
            /** @description 查詢參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFactoryMeasurements: {
        parameters: {
            query?: {
                /**
                 * @description 選擇要回傳的欄位 (逗號分隔)
                 * @example time,device_id,temperature,humidity,pressure
                 */
                select?: string;
                /**
                 * @description 依設備 ID 過濾 (使用 eq.xxx 格式)
                 * @example eq.plc-001
                 */
                device_id?: string;
                /**
                 * @description 依設備類型過濾 (plc 或 sensor)
                 * @example eq.plc
                 */
                device_type?: string;
                /**
                 * @description 依時間過濾 (使用 gte.xxx 或 lte.xxx 格式)
                 * @example gte.2026-04-27T00:00:00
                 */
                time?: string;
                /**
                 * @description 排序欄位 (欄位名.asc 或 欄位名.desc)
                 * @example time.desc
                 */
                order?: string;
                /**
                 * @description 限制回傳筆數
                 * @example 10
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工廠量測資料列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "time": "2026-04-27T09:00:00Z",
                     *         "device_id": "plc-001",
                     *         "device_type": "plc",
                     *         "temperature": 25.3,
                     *         "humidity": 55.2,
                     *         "motor_speed": 1500,
                     *         "pump_on": true,
                     *         "valve_open": false,
                     *         "pressure": 1013
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["FactoryMeasurement"][];
                };
            };
            /** @description 查詢參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reloadAlertingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 告警設定已重新載入 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example alerting config reloaded */
                        message?: string;
                    };
                };
            };
        };
    };
    reloadDashboardsConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 儀表板設定已重新載入 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reloadDatasourcesConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 資料來源設定已重新載入 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 告警規則列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRulesResponse"];
                };
            };
        };
    };
    getActiveAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 觸發中的告警列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAlert"][];
                };
            };
        };
    };
    checkDatasourceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 資料來源的 UID
                 * @example timescaledb-ems
                 */
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 資料來源健康狀態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceHealthResponse"];
                };
            };
        };
    };
    testNotificationReceiver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "receivers": [
                 *         {
                 *           "name": "Telegram",
                 *           "grafana_managed_receiver_configs": [
                 *             {
                 *               "uid": "telegram-main",
                 *               "name": "Telegram",
                 *               "type": "telegram",
                 *               "settings": {
                 *                 "bottoken": "<YOUR_BOT_TOKEN>",
                 *                 "chatid": "7171144544",
                 *                 "message": "EMS 測試訊息"
                 *               }
                 *             }
                 *           ]
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["TestReceiverRequest"];
            };
        };
        responses: {
            /** @description 測試通知已發送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 請求格式錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deviceHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 所有 pool ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description 至少一個 pool degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: {
                status?: string;
                stale?: boolean;
                /** @description 依 device_type 過濾 */
                type?: string;
                /** @description 分頁筆數上限（不給則回全部） */
                limit?: number;
                offset?: number;
                /** @description 排序欄位 allowlist；NULLS LAST，次序鍵 device_id */
                sort?: "device_id" | "device_type" | "status" | "ai_confidence" | "created_at" | "updated_at" | "last_seen_at";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 裝置清單 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description 參數驗證失敗（如 sort 不在 allowlist） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 缺/錯 X-API-Key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 通道不允許 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 裝置已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 裝置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退役 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 凍結裝置，請用 /reject */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 凍結紀錄，請用 /override */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 非 candidate 狀態 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overrideDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description confirmed (manual_override) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAiFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description 已記錄 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionOut"];
                };
            };
            /** @description 內容違規（length/structural/secret/injection/format） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 裝置不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description demote 對非 confirmed 裝置 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 速率限制（per-key 30/h、per-device 10/h，FR-343） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AUDIT_HASH_SALT 未設（audit identity 不可用） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCorrections: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description corrections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionOut"][];
                };
            };
            /** @description 裝置不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivateCorrection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                correction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionDeactivateRequest"];
            };
        };
        responses: {
            /** @description 已失效 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionOut"];
                };
            };
            /** @description reason 內容違規 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 裝置不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description correction 不存在或已失效 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    humanReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description digest（llm 或 system_fallback） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description 裝置不存在或尚無 digest */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSignals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description signals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOut"][];
                };
            };
        };
    };
    addSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalCreate"];
            };
        };
        responses: {
            /** @description 已新增 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOut"];
                };
            };
            /** @description 裝置不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description signal 已 active，或凍結紀錄（請用 /override） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                signal_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退役 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 查無 active signal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 凍結紀錄，請用 /override */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
